export const CURRENT_ADDRESS = 'CURRENT_ADDRESS';
export const CURRENT_CITY = 'CURRENT_CITY';
export const CITIES = 'CITIES';
export const SEARCH_CITIES = 'SEARCH_CITIES';
export const CITY_REQUEST = 'CITY_REQUEST';
export const CITY_REQUEST_FAILED = 'CITY_REQUEST_FAILED';

export const FOOD_TYPES = 'FOOD_TYPES';
export const FOOD_CATEGORY = 'FOOD_CATEGORY';
export const FOOD_REQUEST = 'FOOD_REQUEST';
export const FOOD_REQUEST_FAILED = 'FOOD_REQUEST_FAILED';

export const SHOP_LIST = 'SHOP_LIST';
export const SHOP_DETAIL = 'SHOP_DETAIL';
export const SHOP_MENUS = 'SHOP_MENUS';
export const SHOP_RATING_SCORES = 'SHOP_RATING_SCORES';
export const SHOP_RATING_TAGS = 'SHOP_RATING_TAGS';
export const SHOP_RATING_LIST = 'SHOP_RATING_LIST';
export const SHOP_OFFSET = 'SHOP_OFFSET';
export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_REQUEST_FAILED = 'SHOP_REQUEST_FAILED';
