export const CURRENT_ADDRESS = 'CURRENT_ADDRESS';
export const CURRENT_CITY = 'CURRENT_CITY';
export const CITIES = 'CITIES';
export const SEARCH_CITIES = 'SEARCH_CITIES';
export const CITY_REQUEST = 'CITY_REQUEST';
export const CITY_REQUEST_FAILED = 'CITY_REQUEST_FAILED';

export const FOOD_TYPES = 'FOOD_TYPES';
export const FOOD_REQUEST = 'FOOD_REQUEST';
export const FOOD_REQUEST_FAILED = 'FOOD_REQUEST_FAILED';
